<?php
echo "<script>
var msg = `%cNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNx;,,,:0NNNNNNNNNNNNNNNNNNNNNNXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNx,,,,,,;ONNNNNNNNNNNNNNNNNNNNNXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNc,,,,,,;lNNNNNNNNNNNNNNNNNNNNNXXXXX
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNO:;;;;;:ONNNNNNNNNNNNNNNNNNNNNNXXXN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNXOxddkKNNNNNNNNNNNNNNNNNNNNNNNXXNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNNX0OkkxxkO0XNXNNNNNNNNNNNNNNNNNNNNNNNNXXXXXNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNNNNKOdl:;;,,,,'''',:lx0XNNNNNNNNNNNNNNNNNNNXXXXXXNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNNNKko:;,'''.............';d0XNNNNNNNNNXXXXXXXXXXXXNNNNN
NNNNNNNNNNNNNNNNNNNNNNNNNKxlc:;,'''.................'cOXXXXXXXXXXXXXXXXXXXXXNNXN
NNNNNNNNNNNNNNNNNNNNNNNNKxocc:,''''........      .....'lKXXXXXXXXXXXXXXXXXXXXXXN
NNNNNNNNNNNNNNXNNXNNNXXXkooc:;,''''........       .....':0XXXXXXXXXXXXXXXXXXXXXX
NNNNNNNNNNNNXXXXXXXXXXXOxolc:;,''''''..................',;OXXXXXXXXXXXXXXXXXXXXN
NNNNNNNNNNXXXXXXXXXXXXKkollc:;,,'',,''..................',:KXXXXXXXXXXXXKKXKKKXX
NNNNNNNNXXXXXXXXXXXXXX0dllc::;;,,,,,,''''''','...........',xKKKXXXXKXKKKKKKKKKKK
NNNNNNNXXXXXXXXXXXXXXKOdlccc:::ccclol;,,;,',;:cc;'....,:clcl0KKKKXXXKKKKKKKKKKKK
NNNNNNNNXXXXXXXXXXXKdlc;;coddollcclc:::cooddooolc;'.,c:clolcxOO0KXXXXXKKKKKKKKKK
XXXXXXXXXNNNNNNNNNNxcc:o,';ll:ccccc:;:;::;;;,;:::,'.,ccoooxokxlcOXXXXXXXKKOkkxdd
XXNNNNNNNNWNNNNNNNNc;;':l::cc:;::;;;,'''''''....',,..:;;::coK0,kKXXXXXXKKKKKKKKK
XNNWWWWNNWNNNNNNNNN:,.,ll,,:cc:::;;,,'..........',,..,,.''':KllXXXXXXXXXXXXXXXXX
XNNWWWWNNNNNNWWWWWNo'.'';'.;cc:cc;,,,,,,''.'...',,''..,'...';oNNNNWWWWWWWNNNNXOO
NNNWWWWNNNNNNWWWWWNX:.'.',,;cc:::;,,;;,''''';lc::;;,..,c;',;KNNNNNWWWWWWWWX0xxkk
NWWWWWWNNNNNNWWWWWWNNd,...':cc::;,',c;,'''''':lodxxolc::c,,c0NNNNNWWNXXNWWxokXNX
WNNWWWWNNNNNNWWWWWWNNNN0xodollc:;'.,:,'';cllcc:;;:clc:;;c::coOXXKXNWWXKNWWxloXNN
NNNWWWWNNNNNNWWWWWWWNNNNNdccolcc;,.';'..:lc,'.....',lko:;;;::oOKKK0NNK0NWWkokNNN
NNNWWWWWNNNNNWWWWWWNNNNNNo::lollc;.';'....';::;:;,,;;;..';;;:oOK0kKWWWWWWWXKNNNX
NNNWWWWWNNNNNNNNWWWNNNNN0c;;coool:,,;,......','',;:c;..':c;;:o00NNWWWWNNNNNNWNNX
NNNWWWWWNNWNNNNNWWNNNNNXo:;;:cloooc::;'........'',,,..,lol;;;oOkXNNNWNNNNNNNNNNX
WWNWWWWWNWWWNNNNWXKNNNNkc:;;::cloooolc:,.............,d0xdl;;d00NNWWWWNNWNNWWWNN
WWWWWWWWNWWWWNNXO0XXNXkl:;;;;:cclooddooo:,'.........;OOk0Oxl:x0XNNWWWWWWWWWWWWWN
WWWWWWWWWWWWNNK0O0X0kolc:;,,;::cllooooddxdl:,'....,cO000O00kd0KNNNNNNNNWWNNNNWWN
NWWWNNNXXXNXX0K00xlc::cc;,,,,;;:cllooooddxxkxddodxOOO000000000KNNNNNNNNNNNNXXNWW
xNWWWWNK0OO00OK00kl,;;c:,,'',,,;::clloodddxxxxdoN0XK0OOO0OOOOOO0KKXXNNNNNNNXXXNW
oXKK0Okkk00O000K00kl;;c:,''''''',,:::cloooodolcxNK0X000000000000000XXNNNNNNNKXNW
kxkxkxxkOO0O00OKK0Okdc:;,''''....',;;;;:::cc::cxNNOX0K00000000000KKKK0NWWNNNKKKO
xdxxkOkkkOOkO00O0K0OOOxc''''''''.'',,,'',;:;;:cdX0kX0K0000000000O00KKKKKXNNNNX0k
xkkkkk0OkkOkkO0000KKO0OOd;',,,''.'',;;;;;;,,;:oOOKO00000OOOOOOOOOOO000KKKXNNNXXX
dxkxxkkO00OOkkOO0000KK0Kkdl,,,'....',,,,'.',;lkO0WNx00O000OOOOOOO0O00000KKXNNNKK
dddkOxxxkOK0OkkkkkOOKKKOxkO:,'............',;lkOKXKlO0000OkOOO0OO0000000KKXXNWNN
xxdxx0OxxkxOKKOxkkcd000k..kc'''.............,d0OOO000000OOOOO00OO000000000XXXNNN
dxxxdx00kxxxk0X0xd '0O0KXKk,.................o0XOk000000OO0OO0OO0000000000XXXXXN

chadlavmoniere.com is built by a small team of one engineer, one designer,
(same person), a few robots, and no others in any different sites across the
globe. It is updated sometimes, and made with a number of tools and technologies
than one could feasibly shake a stick at.

If you want to access http://chadlavimoniere.com/portfolio, the login info is:

user: 'phillipjfry'
password: 'hireme'

And if you would like to hire me, email chad@chadlavimoniere.com, and let me
know the console logs sent ya!`

console.log(msg, 'font-family: monospace')</script>";
?>
